config/routes.rb
PppApp::Application.routes.draw do
  root to: 'static_pages#home'
  

  match '/products',      to: 'static_pages#products'
  match '/publications',  to: 'static_pages#publications'
  match '/about',         to: 'static_pages#about'
  match '/contact',       to: 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = 'Picon Punch'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://piconpunch.com/">Picon Punch Press, LLC</a>
			&bullet; 321 S Arlington Ave &bullet; Reno NV, 89501 
			&bullet; (775) 525-1345
	</small>
	<nav>
		<ul>
			<li><%= link_to "Home",       	root_path %></li>
			<li><%= link_to "Products",     products_path %></li>
			<li><%= link_to "Pubs", 				publications_path %></li>
			<li><%= link_to "About",    		about_path %></li>
			<li><%= link_to "Contact",  		contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
		<%= link_to "Picon Punch Press", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",       		root_path %></li>
					<li><%= link_to "Print Products", products_path %></li>
					<li><%= link_to "Publications", 	publications_path %></li>
					<li><%= link_to "About Us",   		about_path %></li>
					<li><%= link_to "Contact Us", 		contact_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http:html5shim.googlecode.com/svn/trunk/html5.js"></script>
<! [endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
		<!-- The next two lines make the website responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>	
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="center hero-unit">
	<h1>About Us</h1>
	<p>
		Picon Punch Press is a publishing company brewed right here in Northern Nevada.  True to the apertif from which it takes its name, Picon Punch Press is bold and bracing offering powerfully conceived, savvily targeted print and digital publications that help its clients create a stir, move the needle and celebrate their message.  Additionally, discriminating tastes fuel high quality print products ranging from business cards and posters, to window clings and yard signs.  In traditional Nevadan style, Picon Punch Press is independently owned and operated free to seek creative paths and discover new destinations.
	</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<div class="center hero-unit">
	<h1>Contact Us</h1>
	<p>We love it when people call us! Feel free to give us a ring at <strong> (775) 525-1345</strong>.</p>
	<p>For lovers of the written word drop us a note: <a style="color: red" href="mailto:info@PiconPunch.com">info@PiconPunch.com</a> </p> 
	<p>Personal visits are great too - stop by and say "Hi!"<br>  We are located at 321 South Arlington Avenue in the beautiful RiverWalk District near downtown Reno.</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>How Can We Help You?</h1>
<p>
	Here are some Frequently Asked Questions (FAQ).
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit"
	<%= link_to image_tag("PiconLogo_MarketDeco_square_300x300_16color.gif", alt: "Picon Punch Press, LLC"), 'http://piconpunch.com' %>
	<h1>Picon Punch Press</h1>
	<p>
		<a href="http://piconpunch.com" style="color: red">Picon Punch Press, LLC</a> publishes <a href="http://ilovereno.com" style="color: red"><em>I Love Reno</em> Magazine</a> and offers professional custom print products for all your business needs.
	</p>
	&nbsp;
	<div class="row-fluid">
		<div class="span3 offset3"><%= link_to "Order Print Products", products_path, class: "btn btn-danger" %></div> 
		&nbsp;
		<div class="span3"><%= link_to "Our Publications", publications_path, class: "btn btn-inverse" %></div>
	</div>
</div>

app/views/static_pages/products.html.erb
<% provide(:title, 'Products') %>
<div class="center hero-unit">
	<h1>Print Products</h1>
	<p>
		Picon Punch Press specializes in high quality print products at extremely competitive prices.  These products include:
	</p>
</div>
<div class="row-fluid">
	<div class="span4 hero-unit zero">
		<h4>Business Cards</h4>
		<p>Full color business cards on high-quality thick stock</p>
		<ul>
			<div class="span6">
				<li>1-sided</li>
			</div>
			<div class="span6">
				<li>2-sided</li>
			</div>
		</ul>
	</div>
	<div class="span4 hero-unit zero">
		<h4>Post Cards</h4>
		<p>One- and 2-sided</p>
		<ul>
			<div class="span6">
				<li>4" x 6"</li>
				<li>5.5" x 8.5"</li>
			</div>
			<div class="span6">
				<li>5" x 7"</li>
				<li>6.5" x 9"</li>
			</div>
		</ul>
	</div>
	<div class="span4 hero-unit zero">
		<h4>Hangtags (Door Hangers)</h4>
		<p>One- and 2-sided</p>
		<ul>
			<div class="span6">
				<li>2" x 5"</li>
			</div>
			<div class="span6">
				<li>2" x 7"</li>
			</div>
		</ul>
	</div>
</div>
&nbsp;
<div class="row-fluid">
	<div class="span4 hero-unit zero">
		<h4>Table Tents</h4>
		<ul>
			<div class="span6">
				<li>4" x 4"</li>
				<li>4" x 6"</li>
			</div>
			<div class="span6">
				<li>5" x 5.5"</li>
			</div>
		</ul>
	</div>
	<div class="span4 hero-unit zero">
		<h4>Window Clings</h4>
		<ul>
			<div class="span6">
				<li>12" x 18"</li>
				<li>16" x 20"</li>
				<li>18" x 24"</li>
				<li>20" x 30"</li>
			</div>
			<div class="span6">
				<li>24" x 36"</li>
				<li>30" x 40"</li>
				<li>32" x 48"</li>
				<li>36" x 48"</li>
			</div>
		</ul>
	</div>
	<div class="span4 hero-unit zero">
		<h4>Window Decals</h4>
		<p>Indoor and Outdoor</p>
		<ul>
			<div class="span6">
				<li>12" x 18"</li>
				<li>16" x 20"</li>
				<li>18" x 24"</li>
				<li>20" x 30"</li>
			</div>
			<div class="span6">
				<li>24" x 36"</li>
				<li>30" x 40"</li>
				<li>32" x 48"</li>
				<li>36" x 48"</li>
			</div>
		</ul>
	</div>
</div>
&nbsp;
<div class="row-fluid">
	<div class="span12 hero-unit zero">
		<h4>And much more!</h4>
		<p><%= link_to "Contact us", contact_path %> with your specific print needs.</p>
	</div>
</div>

app/views/static_pages/publications.html.erb
<% provide(:title, 'Publications') %>
<div class="center hero-unit">
	<h1>Publications</h1>
	<p>
		With more publications to come, our most recent is <em><span style="font-family: courier">  I <i class="icon-heart"></i> RENO </span> Magazine</em>.
	</p>
</div>
&nbsp;
<div class="center hero-unit zero">
	<a href="http://ilovereno.com/">
	<img alt="I Love Reno Magazine" src="/assets/ILR-masthead-862x232.jpg" height="116" width="431" /></a>
	<p style="clear:left;"></p>
	<br class="blank" />
	<p>
		A fresh new magazine, <em style="font-family: courier">  I <i class="icon-heart"></i> RENO</em> focuses on local residents, business, and events at the neighborhood level.  There is a lot to love about this town, and this magazine captures local information and shares with the neighbors.  The inaugural edition focuses on the beautiful Southwest region of Reno with its picturesque streets, beautiful architecture, and welcoming residents.  USPS will distribute 10,000 copies to parts of 89509 and 89519 zip codes and additional 1,000 copies will be available for pick-up at local retail and dining establishments.  We love Reno and want to spread the love! Join us by showcasing your business to your Southwest neighbors.
	</p>
	&nbsp;
	<p>
		<a href="http://ilovereno.com/">
			<button class="btn btn-large btn-danger" style="font-family: courier; color: white">
				I <i class="icon-heart icon-white"></i> RENO <em style="font-family: sans-serif; color: #faa"> Magazine</em>  <i class="icon-chevron-right icon-white"></i>
			</button>
		</a>
	</p>
</div>